// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is auto-generated by json_serializable

part of 'addon_manifest.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AddonManifest _$AddonManifestFromJson(Map<String, dynamic> json) =>
    AddonManifest(
      id: json['id'] as String,
      version: json['version'] as String,
      name: json['name'] as String,
      description: json['description'] as String?,
      logo: json['logo'] as String?,
      author: json['author'] as String?,
      resources: List<Map<String, dynamic>>.from(json['resources'] as List),
      types: List<String>.from(json['types'] as List),
      idPrefixes: (json['idPrefixes'] as List?)?.map((e) => e as String).toList(),
      catalogs: (json['catalogs'] as List?)
          ?.map((e) => CatalogResource.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$AddonManifestToJson(AddonManifest instance) =>
    <String, dynamic>{
      'id': instance.id,
      'version': instance.version,
      'name': instance.name,
      'description': instance.description,
      'logo': instance.logo,
      'author': instance.author,
      'resources': instance.resources,
      'types': instance.types,
      'idPrefixes': instance.idPrefixes,
      'catalogs': instance.catalogs,
    };

CatalogResource _$CatalogResourceFromJson(Map<String, dynamic> json) =>
    CatalogResource(
      type: json['type'] as String,
      id: json['id'] as String,
      name: json['name'] as String?,
      extra: (json['extra'] as List?)?.map((e) => Map<String, dynamic>.from(e as Map)).toList(),
    );

Map<String, dynamic> _$CatalogResourceToJson(CatalogResource instance) =>
    <String, dynamic>{
      'type': instance.type,
      'id': instance.id,
      'name': instance.name,
      'extra': instance.extra,
    };
